name: SONCHOIGAME

options:
  bundleIdPrefix: com.sonchoigame
  deploymentTarget:
    iOS: "16.0"

packages:
  OpenSSL:
    url: https://github.com/21-DOT-DEV/swift-openssl.git
    exactVersion: 0.1.0

targets:
  SONCHOIGAME:
    type: application
    platform: iOS

    sources:
      - path: SONCHOIGAME

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sonchoigame.p12tool
        PRODUCT_NAME: SONCHOIGAME

        SWIFT_VERSION: "5.0"

        SWIFT_OBJC_BRIDGING_HEADER: SONCHOIGAME/Bridge/SONCHOIGAME-Bridging-Header.h

        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: SONCHOIGAME
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
        INFOPLIST_KEY_UIFileSharingEnabled: YES

        IPHONEOS_DEPLOYMENT_TARGET: "16.0"

    dependencies:
      - package: OpenSSL
        product: OpenSSL
